### ISSUE TITLE
Additional not required android permissions in manifest file issue

### ISSUE THREAD

**Issue by pichurichko** [AppsFlyerSDK/appsflyer-nativescript-plugin#23]
Additional permissions can be created in apps manifest after adding appsflyer plugin and build.
For example in my case WRITE_EXTERNAL_STORAGE access was added into main app manifest, by I do not require it.

It can be caused by merge with demo app AndroidManifest.xml file.

**Comment by mrmaakun** [comment]
Hi @pichurichko,

This looks like it's being caused by [Google's Play Install Referrer Library v1.1](https://stackoverflow.com/questions/59369092/play-install-referrer-library-adding-write-external-storage-and-read-external-st), which we include in the plugin. We went ahead and [downgraded the version that we include to 1.0 to fix this problem](https://github.com/AppsFlyerSDK/appsflyer-nativescript-plugin/commit/dde95b1da3f05d720dbd0c347f0b49a8d98db081). Please try the latest version of the plugin out.

**Comment by af-fess** [comment]
Released [v1.1.2](https://mvnrepository.com/artifact/com.android.installreferrer/installreferrer/1.1.2)
